# Generated by Django 5.2.15 on 2026-06-23 15:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("under_500", "< $500"),
                    ("500_1500", "$500 to $1500"),
                    ("1500_5000", "$1500 to $5000"),
                    ("over_5000", "$5000+"),
                ],
                max_length=20,
            ),
        ),
    ]
