# Generated by Django 5.2.15 on 2026-06-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_alter_booking_budget_range"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="budget_range",
            field=models.CharField(
                choices=[
                    ("under_500", "< $500 · < TZS 1,300,000"),
                    ("500_1500", "$500 – $1,500 · TZS 1,300,000 – TZS 3,900,000"),
                    ("1500_5000", "$1,500 – $5,000 · TZS 3,900,000 – TZS 13,000,000"),
                    ("over_5000", "Over $5,000 · Over TZS 13,000,000"),
                ],
                max_length=20,
            ),
        ),
    ]
